spring:
  application:
    name: stadium

  datasource:
    url: jdbc:postgresql://postgres:5432/stadiumdb
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # create | create-drop | update | validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

retrofit:
  api-football-connector:
    url: https://apiv3.apifootball.com/
    api-key: ebf4794ab2981dfbb0fd8ac4278a48922a8dba87d5295126b17a510a5224bee2
    read-timeout: 5000
    connection-timeout: 3000

logging:
  level:
    org.springframework.security: DEBUG
